[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
thickness = 0.2
unfocused_hollow = true

[font]
size = 14.0

[font.normal]
family = "MesloLGL Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001B[66;5ui"
key = "I"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B/"
key = "Slash"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BA"
key = "A"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BB"
key = "B"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BC"
key = "C"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BD"
key = "D"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BE"
key = "E"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "F"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BG"
key = "G"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BI"
key = "I"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BM"
key = "M"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BN"
key = "N"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BO"
key = "O"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BP"
key = "P"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BQ"
key = "Q"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BS"
key = "S"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BT"
key = "T"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BU"
key = "U"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BV"
key = "V"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BY"
key = "Y"
mods = "Command | Shift"

[[keyboard.bindings]]
chars = "\u001BZ"
key = "Z"
mods = "Command | Shift"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "zsh"

[window]
opacity = 1.0
startup_mode = "Maximized"
